version: '3.6'
services:
  nbs_api:
    image: nearbyshops/nearbyshops
    ports:
      - "80:80"
    container_name: nbs_api_container
    volumes:
      - db_data:/var/lib/postgresql/12/main
      - api_data:/root/nearbyshops/data
    restart: always
    entrypoint: ["/root/nbs.sh"]


volumes:
    db_data:
    api_data:
